project_id = "fcmwixdlmbauyznvcfti"

[functions.validate-project-setup]
verify_jwt = false

[functions.telegram-bot-handler]
verify_jwt = false

[functions.check-expiring-subscriptions]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false
